---
- name: 'Include tasks to ensure variables are defined properly'
  ansible.builtin.include_tasks:
    file: 'assert.yml'

- name: 'Include tasks to create hosts in Satellite: {{ __t_sat_host }}'
  ansible.builtin.include_tasks:
    file: 'create_host.yml'
  vars:
    __host: '{{ __t_host }}'
  loop: '{{ _sat_hosts }}'
  loop_control:
    loop_var: '__t_host'
...
